server:
  port: 8003
spring:
  application:
    name: service_vod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB   #文件上传单个文件最大 ，默认是1MB
      max-request-size: 1024MB #最大置总上传数据大小为 默认是10MB


#阿里云oss
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid:  LTAI4FjWa9vboNKj7NxGpLTW
      keysecret:  deCyHlvBqywIa6LOjl8XP8WLBPcHkR
      bucketname: edu-itguigu

