server:
  port: 8001
spring:
  application:
    name: service-edu
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #nacos服务地址
    gateway:  #使用服务发路由
      discovery:
        locator:
          enabled: true
      routes[0].id: service-acl  #设置路由的id
      routes[0].url:  lb://service-acl
      routes[0].predicates:
