server:
  port: 8004
spring:
  application:
    name: service-educms
  profiles:
    active: dev #这是环境配置有dev  test  prod
    #配置数据连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
    password: root123456
    #返回JSON的全局格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #nacos服务地址
  redis: #redis相关配置
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1  #最大阻塞等待时间（负数表示没有限制）
        max-idle: 5
        min-idle: 0




      #mp日志
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml  #mp的扫描xml路径配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

      # mapper-locations: classpath:mappers/**.xml

feign:
  hystrix:
    enabled: true  #true表示开启熔断器