server:
  port: 8002
spring:
  application:
    name: service_oss
  profiles:
    active: dev

#阿里云oss
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid:  LTAI4FjWa9vboNKj7NxGpLTW
      keysecret:  deCyHlvBqywIa6LOjl8XP8WLBPcHkR
      bucketname: edu-itguigu
